---
debug: info # fatal, error, warn, info, debug; defaults to 'fatal'
logfile: stderr # stderr, stdout, or path; defaults to log/ordnung.log
title: Ordnung
theme: cosmo # One of cerulean cosmo cyborg darkly flatly journal lumen paper readable sandstone simplex slate spacelab superhero united yeti (see http://bootswatch.com). Leave empty for default
port: # Specify a port where you can reach the webinterface, or (default) 4567

# see lib/ordnung/database
database: elasticsearch

elasticsearch:
  index: "ordnung"
  mapping:
    dynamic: strict
    properties:
      type:
       type: keyword
      ctime:
        type: date
      locations:
        type: keyword
      mimetype:
        type: keyword
      mtime:
        type: date
      name:
        type: keyword
      size:
        type: long
      tags:
        type: keyword

mimetypes:
  - mime.types
  - yml: text/plain
